//! # serde_versioned
//!
//! A library for handling versioned serialization and deserialization of Rust structs.
//! This crate provides traits and derive macros to support multiple versions of data structures
//! while maintaining backward compatibility.
//!
//! ## Usage
//!
//! ```rust,no_run
//! use serde_versioned::{Versioned, FromVersion};
//! use serde::{Serialize, Deserialize};
//!
//! #[derive(Versioned, Serialize, Deserialize, Clone)]
//! #[versioned(versions = [UserV1, UserV2])]
//! struct User {
//!     pub name: String,
//!     pub age: u32,
//! }
//!
//! #[derive(Serialize, Deserialize, Clone)]
//! pub struct UserV1 {
//!     pub name: String,
//! }
//!
//! #[derive(Serialize, Deserialize, Clone)]
//! pub struct UserV2 {
//!     pub name: String,
//!     pub age: u32,
//! }
//!
//! impl FromVersion<User> for UserV1 {
//!     fn convert(self) -> User {
//!         User { name: self.name, age: 0 }
//!     }
//! }
//!
//! impl FromVersion<User> for UserV2 {
//!     fn convert(self) -> User {
//!         User { name: self.name, age: self.age }
//!     }
//! }
//! ```

use serde::{Deserialize, Serialize};
use std::error::Error;

pub use serde_versioned_derive::Versioned;

/// Trait for converting from a versioned struct to the current struct.
///
/// This trait must be implemented for each version struct to define how it converts
/// to the current version of the struct.
///
/// # Example
///
/// ```rust,no_run
/// use serde_versioned::FromVersion;
///
/// struct User { name: String, age: u32 }
/// struct UserV1 { name: String }
///
/// impl FromVersion<User> for UserV1 {
///     fn convert(self) -> User {
///         User { name: self.name, age: 0 }
///     }
/// }
/// ```
pub trait FromVersion<T>: Sized {
    /// Converts a versioned struct instance to the current struct type.
    ///
    /// # Arguments
    ///
    /// * `self` - The versioned struct instance to convert
    ///
    /// # Returns
    ///
    /// The converted current struct instance
    fn convert(self) -> T;
}

/// Trait for handling versioned serialization and deserialization.
///
/// This trait is automatically derived using the `#[derive(Versioned)]` macro.
/// It provides methods to convert between the current struct and its versioned enum.
///
/// # Example
///
/// ```rust,no_run
/// use serde_versioned::Versioned;
/// use serde_json;
///
/// #[derive(Versioned)]
/// #[versioned(versions = [UserV1, UserV2])]
/// struct User { /* ... */ }
///
/// // Convert to versioned enum
/// let user = User { /* ... */ };
/// let version = user.to_version();
///
/// // Serialize to JSON
/// let json = serde_json::to_string(&version).unwrap();
///
/// // Deserialize and convert back
/// let version: UserVersion = serde_json::from_str(&json).unwrap();
/// let user = User::from_version(version).unwrap();
/// ```
pub trait Versioned: Sized {
    /// The version enum type that represents all versions of this struct.
    ///
    /// This enum is automatically generated by the `#[derive(Versioned)]` macro
    /// and contains variants for each version specified in the `versions` attribute.
    type VersionEnum: for<'a> Deserialize<'a> + Serialize;
    
    /// Converts a versioned enum instance back to the current struct.
    ///
    /// # Arguments
    ///
    /// * `version` - The versioned enum instance to convert
    ///
    /// # Returns
    ///
    /// * `Ok(Self)` - Successfully converted struct
    /// * `Err(Box<dyn Error + Send + Sync>)` - Error during conversion
    ///
    /// # Errors
    ///
    /// Returns an error if the conversion from the versioned struct to the current struct fails.
    /// This typically happens when the `FromVersion` implementation fails.
    fn from_version(version: Self::VersionEnum) -> Result<Self, Box<dyn Error + Send + Sync>>;
    
    /// Converts the current struct instance to its versioned enum representation.
    ///
    /// This always uses the latest version specified in the `versions` attribute.
    ///
    /// # Returns
    ///
    /// The versioned enum instance representing this struct in its latest version.
    fn to_version(&self) -> Self::VersionEnum;

    /// Deserializes from a string format and converts to the current struct.
    ///
    /// This is a convenience method that combines deserialization and version conversion.
    ///
    /// # Arguments
    ///
    /// * `input` - The string to deserialize from
    /// * `deserializer` - A function that deserializes the string into `Self::VersionEnum`
    ///
    /// # Returns
    ///
    /// * `Ok(Self)` - Successfully deserialized and converted struct
    /// * `Err(FormatError<E>)` - Error during deserialization or conversion
    ///
    /// # Errors
    ///
    /// Returns `FormatError::Deserialize` if deserialization fails, or
    /// `FormatError::VersionConversion` if version conversion fails.
    ///
    /// # Example
    ///
    /// ```rust,no_run
    /// use serde_versioned::Versioned;
    ///
    /// let json = r#"{"version":"1","name":"Alice"}"#;
    /// let user = User::from_format(json, |s| serde_json::from_str(s)).unwrap();
    /// ```
    fn from_format<'a, F, E>(input: &'a str, deserializer: F) -> Result<Self, FormatError<E>>
    where
        F: FnOnce(&'a str) -> Result<Self::VersionEnum, E>,
        E: Error + Send + Sync + 'static,
    {
        let version = deserializer(input)
            .map_err(FormatError::Deserialize)?;
        Self::from_version(version)
            .map_err(FormatError::VersionConversion)
    }
    
    /// Serializes the current struct to a string format via its versioned enum.
    ///
    /// This is a convenience method that converts the struct to its versioned enum
    /// and then serializes it using the provided serializer function.
    ///
    /// # Arguments
    ///
    /// * `serializer` - A function that serializes `Self::VersionEnum` to the desired format
    ///
    /// # Returns
    ///
    /// * `Ok(T)` - Successfully serialized data
    /// * `Err(E)` - Error during serialization
    ///
    /// # Example
    ///
    /// ```rust,no_run
    /// use serde_versioned::Versioned;
    ///
    /// let user = User { name: "Alice".to_string(), age: 30 };
    /// let json = user.to_format(|v| serde_json::to_string(v)).unwrap();
    /// ```
    fn to_format<F, T, E>(&self, serializer: F) -> Result<T, E>
    where
        F: FnOnce(&Self::VersionEnum) -> Result<T, E>,
    {
        let version = self.to_version();
        serializer(&version)
    }
}

/// Error type for format conversion operations.
///
/// This enum represents errors that can occur when using `from_format` or `to_format` methods.
#[derive(Debug)]
pub enum FormatError<E> {
    /// Error occurred during deserialization of the input string.
    Deserialize(E),
    /// Error occurred during conversion from a versioned struct to the current struct.
    VersionConversion(Box<dyn Error + Send + Sync>),
}

impl<E: Error + Send + Sync + 'static> Error for FormatError<E> {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            FormatError::Deserialize(e) => Some(e),
            FormatError::VersionConversion(e) => Some(e.as_ref()),
        }
    }
}

impl<E: Error + Send + Sync + 'static> std::fmt::Display for FormatError<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            FormatError::Deserialize(e) => write!(f, "Deserialization error: {}", e),
            FormatError::VersionConversion(e) => write!(f, "Version conversion error: {}", e),
        }
    }
}